spring:
  application:
    name=config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:classpath:/configurations #caminho configs

server:
  port:8888